"""add seat table and update booking slot relationship

Revision ID: daa6e5425bed
Revises: b6d43d51938a
Create Date: 2026-02-10 08:58:57.504955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa6e5425bed'
down_revision: Union[str, Sequence[str], None] = 'b6d43d51938a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('seat_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('seat_type', sa.String(), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seats_slot_id'), 'seats', ['slot_id'], unique=False)
    op.add_column('bookings', sa.Column('seat_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_bookings_slot_id'), table_name='bookings')
    op.create_index(op.f('ix_bookings_seat_id'), 'bookings', ['seat_id'], unique=False)
    op.drop_constraint(op.f('bookings_slot_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'seats', ['seat_id'], ['id'])
    op.drop_column('bookings', 'slot_id')
    op.drop_column('slots', 'capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('slot_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_slot_id_fkey'), 'bookings', 'slots', ['slot_id'], ['id'])
    op.drop_index(op.f('ix_bookings_seat_id'), table_name='bookings')
    op.create_index(op.f('ix_bookings_slot_id'), 'bookings', ['slot_id'], unique=False)
    op.drop_column('bookings', 'seat_id')
    op.drop_index(op.f('ix_seats_slot_id'), table_name='seats')
    op.drop_table('seats')
    # ### end Alembic commands ###
